done

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,18 +33,18 @@ jobs:
         id:   gitversion 
         uses: gittools/actions/gitversion/execute@v0
 
-      - name: Git-Secret Validation
-        run: |
-          sudo apt-get update && sudo apt-get -y install git-secrets
-          echo "Security check started before build"
-          echo "Checking for any secrets stored in the repo using git-secrets"
-          if ! git-secrets --scan -r $PWD; then
-              echo "CI Job Aborting as there is Secret Stored in the Repository."
-              exit 1
-          else 
-              echo "No Secret found in the code" 
-              echo "Proceed for next step....."                            
-          fi
+      # - name: Git-Secret Validation
+      #   run: |
+      #     sudo apt-get update && sudo apt-get -y install git-secrets
+      #     echo "Security check started before build"
+      #     echo "Checking for any secrets stored in the repo using git-secrets"
+      #     if ! git-secrets --scan -r $PWD; then
+      #         echo "CI Job Aborting as there is Secret Stored in the Repository."
+      #         exit 1
+      #     else 
+      #         echo "No Secret found in the code" 
+      #         echo "Proceed for next step....."                            
+      #     fi
 
       - name: Directory For Jfrog Artifactory
         env:
@@ -55,27 +55,27 @@ jobs:
           mkdir -p $VERSION/Build-reports
           mkdir -p $VERSION/Build-configuration
 
-      - name: Setup Java
-        uses: actions/setup-java@v1
-        with:
-          java-version: '17'
+      # - name: Setup Java
+      #   uses: actions/setup-java@v1
+      #   with:
+      #     java-version: '17'
 
-      - name: Build with Maven
-        run: cd Java && mvn clean package
+      # - name: Build with Maven
+      #   run: cd Java && mvn clean package
 
       - name : Jfrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:
-          JF_URL: ${{ secrets.JFrogArtifactory }}
+          JF_URL: kyndryl.jfrog.io
           JF_USER: ${{ secrets.JfrogUser }}
           JF_PASSWORD: ${{ secrets.JfrogUserAPIKey }}
           JF_SERVER_ID : "SERVER"
       - run: |
            jf rt ping
 
-      - name: Upload to JFrog Artifactory
-        run: |
-          jf rt upload --recursive=true --flat=false --url ${{ secrets.JFrogArtifactory }} $VERSION/ ${{ env.JfrogGoRepo }}/${{ env.applicatonName }}/
+      # - name: Upload to JFrog Artifactory
+      #   run: |
+      #     jf rt upload --recursive=true --flat=false --url ${{ secrets.JFrogArtifactory }} $VERSION/ ${{ env.JfrogGoRepo }}/${{ env.applicatonName }}/
 
 
       # - name: Install Snyk CLI
